**Create a 1D array of numbers from 0 to 9**

In [5]:
import numpy

import numpy

arr = numpy.array([1, 2, 3, 4, 5,6,7,8,9])

print(arr)

[1 2 3 4 5 6 7 8 9]


Create a 2D array with shape (3, 3), where values range from 1 to 9.

In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9]])

print(arr)


[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


**Create a 3D array of shape (2, 3, 4) filled with random integers from 1 to 100**.

In [8]:
import numpy as np

arr3 = np.array([[[1,2,0], [2,1,0], [4,3,0]],
 [[1,2,3], [4,3,2], [3,3,3]],
 [[4,3,2], [1,2,3], [4,4,4]]])

print(arr3)

[[[1 2 0]
  [2 1 0]
  [4 3 0]]

 [[1 2 3]
  [4 3 2]
  [3 3 3]]

 [[4 3 2]
  [1 2 3]
  [4 4 4]]]


**Task 2: Array Indexing and Slicing**
**Given the array arr2 from Task 1, extract the second row.**

In [10]:
import numpy as np
second_row = arr[1, :]
print(second_row)

[1 2 3 4 5 6 7 8 9]
